/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Enums-Check.h.zapt

#pragma once

#include <clusters/ProximityRanging/Enums.h>

namespace chip {
namespace app {
namespace Clusters {
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::DeviceRoleEnum val)
{
    using EnumType = ProximityRanging::DeviceRoleEnum;
    switch (val)
    {
    case EnumType::kInitiator:
    case EnumType::kResponder:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::RadioBandEnum val)
{
    using EnumType = ProximityRanging::RadioBandEnum;
    switch (val)
    {
    case EnumType::kBand2400MHz:
    case EnumType::kBand5GHz:
    case EnumType::kBand6GHz:
    case EnumType::kBand60GHz:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::RangingBandwidthEnum val)
{
    using EnumType = ProximityRanging::RangingBandwidthEnum;
    switch (val)
    {
    case EnumType::kBW1MHz:
    case EnumType::kBW2MHz:
    case EnumType::kBW20MHz:
    case EnumType::kBW40MHz:
    case EnumType::kBW80MHz:
    case EnumType::kBW160MHz:
    case EnumType::kBW320MHz:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::RangingSecurityEnum val)
{
    using EnumType = ProximityRanging::RangingSecurityEnum;
    switch (val)
    {
    case EnumType::kNone:
    case EnumType::kMACEncryption:
    case EnumType::kAuthentication:
    case EnumType::kPHYSecurity:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::RangingTechEnum val)
{
    using EnumType = ProximityRanging::RangingTechEnum;
    switch (val)
    {
    case EnumType::kWiFiUSDProximityDetection:
    case EnumType::kBluetoothChannelSounding:
    case EnumType::kUWBRanging:
    case EnumType::kBLEBeaconRSSI:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(ProximityRanging::ResultCodeEnum val)
{
    using EnumType = ProximityRanging::ResultCodeEnum;
    switch (val)
    {
    case EnumType::kAccepted:
    case EnumType::kInfeasibleRFRangingConfiguration:
    case EnumType::kInfeasibleRangingTriggers:
    case EnumType::kSessionCapacityReached:
    case EnumType::kOccupied:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
} // namespace Clusters
} // namespace app
} // namespace chip
