/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Enums.h.zapt

#pragma once

#include <clusters/shared/Enums.h>
#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace ProximityRanging {

// Enum for DeviceRoleEnum
enum class DeviceRoleEnum : uint8_t
{
    kInitiator = 0x00,
    kResponder = 0x01,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 2,
};

// Enum for RadioBandEnum
enum class RadioBandEnum : uint8_t
{
    kBand2400MHz = 0x00,
    kBand5GHz    = 0x01,
    kBand6GHz    = 0x02,
    kBand60GHz   = 0x03,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 4,
};

// Enum for RangingBandwidthEnum
enum class RangingBandwidthEnum : uint8_t
{
    kBW1MHz   = 0x00,
    kBW2MHz   = 0x01,
    kBW20MHz  = 0x02,
    kBW40MHz  = 0x03,
    kBW80MHz  = 0x04,
    kBW160MHz = 0x05,
    kBW320MHz = 0x06,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 7,
};

// Enum for RangingSecurityEnum
enum class RangingSecurityEnum : uint8_t
{
    kNone           = 0x00,
    kMACEncryption  = 0x01,
    kAuthentication = 0x02,
    kPHYSecurity    = 0x03,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 4,
};

// Enum for RangingTechEnum
enum class RangingTechEnum : uint8_t
{
    kWiFiUSDProximityDetection = 0x00,
    kBluetoothChannelSounding  = 0x01,
    kUWBRanging                = 0x02,
    kBLEBeaconRSSI             = 0x03,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 4,
};

// Enum for ResultCodeEnum
enum class ResultCodeEnum : uint8_t
{
    kAccepted                         = 0x00,
    kInfeasibleRFRangingConfiguration = 0x01,
    kInfeasibleRangingTriggers        = 0x02,
    kSessionCapacityReached           = 0x03,
    kOccupied                         = 0x04,
    // All received enum values that are not listed above will be mapped
    // to kUnknownEnumValue. This is a helper enum value that should only
    // be used by code to process how it handles receiving and unknown
    // enum value. This specific should never be transmitted.
    kUnknownEnumValue = 5,
};

// Bitmap for Feature
enum class Feature : uint32_t
{
    kWiFiUsdProximityDetection = 0x1,
    kBluetoothChannelSounding  = 0x2,
    kUwbRanging                = 0x4,
    kBleBeaconRssi             = 0x8,
};
} // namespace ProximityRanging
} // namespace Clusters
} // namespace app
} // namespace chip
