/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace ProximityRanging {
namespace Structs {
namespace RDRStruct {
enum class Fields : uint8_t
{
    kAzimuth           = 0,
    kElevation         = 1,
    kAzimuthAccuracy   = 2,
    kElevationAccuracy = 3,
    kReference         = 4,
};

struct Type
{
public:
    int16_t azimuth           = static_cast<int16_t>(0);
    int8_t elevation          = static_cast<int8_t>(0);
    uint8_t azimuthAccuracy   = static_cast<uint8_t>(0);
    uint8_t elevationAccuracy = static_cast<uint8_t>(0);
    int8_t reference          = static_cast<int8_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RDRStruct
namespace RangingMeasurementDataStruct {
enum class Fields : uint8_t
{
    kWiFiDevIK         = 0,
    kBLEDeviceId       = 1,
    kTimeOfMeasurement = 2,
    kDistance          = 3,
    kAccuracy          = 4,
    kRdr               = 5,
    kRssi              = 6,
    kTxPower           = 7,
};

struct Type
{
public:
    Optional<chip::ByteSpan> wiFiDevIK;
    Optional<uint64_t> BLEDeviceId;
    uint32_t timeOfMeasurement = static_cast<uint32_t>(0);
    int16_t distance           = static_cast<int16_t>(0);
    Optional<uint16_t> accuracy;
    Optional<Structs::RDRStruct::Type> rdr;
    Optional<int8_t> rssi;
    Optional<int8_t> txPower;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingMeasurementDataStruct
namespace BLERangingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole            = 0,
    kPeerBLEDeviceID = 1,
    kPmk             = 2,
};

struct Type
{
public:
    DeviceRoleEnum role      = static_cast<DeviceRoleEnum>(0);
    uint64_t peerBLEDeviceID = static_cast<uint64_t>(0);
    Optional<chip::ByteSpan> pmk;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace BLERangingDeviceRoleConfigStruct
namespace BTChannelSoundingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole            = 0,
    kTargetPeerDevIK = 1,
    kPmk             = 2,
};

struct Type
{
public:
    DeviceRoleEnum role = static_cast<DeviceRoleEnum>(0);
    chip::ByteSpan targetPeerDevIK;
    Optional<chip::ByteSpan> pmk;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace BTChannelSoundingDeviceRoleConfigStruct
namespace RangingCapabilitiesStruct {
enum class Fields : uint8_t
{
    kTechnology             = 0,
    kFrequencyBand          = 1,
    kMobilitySupport        = 2,
    kPeriodicRangingSupport = 3,
};

struct Type
{
public:
    RangingTechEnum technology  = static_cast<RangingTechEnum>(0);
    RadioBandEnum frequencyBand = static_cast<RadioBandEnum>(0);
    bool mobilitySupport        = static_cast<bool>(0);
    bool periodicRangingSupport = static_cast<bool>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingCapabilitiesStruct
namespace RangingTriggerConditionStruct {
enum class Fields : uint8_t
{
    kStartTimeDelay          = 0,
    kEndTimeDelay            = 1,
    kRangingInstanceInterval = 2,
};

struct Type
{
public:
    uint32_t startTimeDelay = static_cast<uint32_t>(0);
    Optional<uint32_t> endTimeDelay;
    Optional<uint32_t> rangingInstanceInterval;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingTriggerConditionStruct
namespace ReportingConditionStruct {
enum class Fields : uint8_t
{
    kMinDistanceCondition = 0,
    kMaxDistanceCondition = 1,
    kAccuracyCondition    = 2,
    kStartTimePeriod      = 3,
    kEndTimePeriod        = 4,
};

struct Type
{
public:
    Optional<int16_t> minDistanceCondition;
    Optional<int16_t> maxDistanceCondition;
    Optional<int16_t> accuracyCondition;
    Optional<uint32_t> startTimePeriod;
    Optional<uint32_t> endTimePeriod;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace ReportingConditionStruct
namespace UWBRangingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole            = 0,
    kTargetPeerDevIK = 1,
    kPASNCredential  = 2,
};

struct Type
{
public:
    DeviceRoleEnum role = static_cast<DeviceRoleEnum>(0);
    chip::ByteSpan targetPeerDevIK;
    Optional<chip::ByteSpan> PASNCredential;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace UWBRangingDeviceRoleConfigStruct
namespace WiFiRangingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole            = 0,
    kTargetPeerDevIK = 1,
    kPmk             = 2,
};

struct Type
{
public:
    DeviceRoleEnum role = static_cast<DeviceRoleEnum>(0);
    chip::ByteSpan targetPeerDevIK;
    Optional<chip::ByteSpan> pmk;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace WiFiRangingDeviceRoleConfigStruct
} // namespace Structs
} // namespace ProximityRanging
} // namespace Clusters
} // namespace app
} // namespace chip
